[profile.default]
src = 'src'
out = './../backend/src/blockchain'
libs = ['lib']
broadcast = './../backend/src/blockchain'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config